version: "2.4"
services:
  femtostats:
    image: ghcr.io/statico/femtostats
    container_name: femtostats
    volumes:
      - ~/stats:/data
    environment:
      DATA_DIR: /data
      PASSWORD: sekrit
      MAXMIND_GEOLITE2_COUNTRY_URL: https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=YOUR_LICENSE_KEY&suffix=tar.gz
    ports:
      - "127.0.0.1:3000:3000"
    restart: always
